### ISSUE TITLE
Accessing direct url show account pages

### ISSUE THREAD

**Issue by web-programmer-here** [nextacular/nextacular#20]
If you access the link directly without login you can see partial account pages 
https://demo.nextacular.co/account

**Comment by arjayosma** [comment]
This actually needs an improvement on the loading strategy.
Currently, Nextacular supports different loading strategies on different parts of the app.
We're waiting for the improvement on this RFC (https://nextjs.org/blog/layouts-rfc) to improve the loading of our apps.

**Comment by arjayosma** [comment]
@web-programmer-here closing this issue as this was resolved by @madhurjain.

Check this PR: https://github.com/nextacular/nextacular/pull/30
