### ISSUE TITLE
Add a database seeding script

### ISSUE THREAD

**Issue by luizov** [nextacular/nextacular#29]
Would you consider adding a seeding script for initially populating the database with data, i.e. with sample users/members.
I think this would greatly improve the developer experience. 

A possible solution would be to add a `seed.js` file in the `/prisma` folder that every dev can run **if** they want or maybe automatically with `prisma migrate`.
What do you think?

**Comment by arjayosma** [comment]
Hi @luizov!

Thanks for this awesome suggestion.
I'll take a look at this one and see if we can add this in the interim.

There's documentation byPprisma in terms of seeding. It might be a good idea to add it as a script to `package.json`, but let's see.
https://www.prisma.io/docs/guides/database/seed-database

**Comment by luizov** [comment]
Yep, exactly what I had in mind. If I manage to come up with a sample `seed.js` I will update you, let's hope I don't mess up the model relations when creating the sample records :)

**Comment by arjayosma** [comment]
Resolved in #41
