### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by mrn3** [nextacular/nextacular#32]
**Is your feature request related to a problem? Please describe.**
For integrating other nextjs stuff on React 18, it would be nice to have this upgraded.

**Describe the solution you'd like**
Upgrade to React 18.

**Describe alternatives you've considered**
Using React 17 or having a directory within my project on React 18 is a pain.

**Comment by arjayosma** [comment]
Thanks, @mrn3! I'll take a look at what needs to be done with this.

**Comment by mrn3** [comment]
ok great thanks!

**Comment by arjayosma** [comment]
hey @mrn3 :D we've updated the demo branch and upgraded the dependency/library versions, you may check it out here:

https://github.com/nextacular/nextacular/tree/demo

Breaking changes:
1. HeroIcons is now using v2, which uses (some) different icon sets and a different import style
2. `_middleware.js` file is now located in the top-level directory of source files and renamed into `middleware.js`

let me know if you encounter any issues :D

**Comment by mrn3** [comment]
Great - thanks so much!

So are you saying those breaking changes will impact me if I depend on those?

**Comment by navjotdhanawat** [comment]
@arjayosma I have upgraded Nextjs to version 13.x, it is tested and everything looks good to me. Please review the [PR](https://github.com/nextacular/nextacular/pull/36) and let me know if there is anything.

cc: @mrn3

**Comment by arjayosma** [comment]
Closing this now. Thanks @navjotdhanawat!
