### ISSUE TITLE
migrate to typescript

### ISSUE THREAD

**Issue by maybesmurf** [nextacular/nextacular#9]
Typescript is already the defacto mainstream for any serious project out there, i'm not sure why it's not written in typescript in the first place. It's still not too late to start migration piece by piece before the project gets too large.

**Comment by arjayosma** [comment]
thanks @maybesmurf! I agree most projects right now are written in TS and it's a good choice.

it was my deliberate choice to work on JS initially as it was intended for early stage founders who are not akin to working with TS to answer your uncertainty.

a TS implementation is on the way, though. care to share some contributions on TS migration? 🙂

**Comment by maybesmurf** [comment]
> care to share some contributions on TS migration?

Definitely. I'll be most glad to. Though the base structure needs to be set up so i (other contributors as well) can all follow the same pattern to enforce consistency all round

**Comment by arjayosma** [comment]
awesome! I'm looking forward to this one. let me know what you need to proceed :)

**Comment by monoppa** [comment]
A tool to help migrate JavaScript code quickly and conveniently to TypeScript
https://github.com/airbnb/ts-migrate

**Comment by fredguth** [comment]
There is a typescript branch, right?

**Comment by arjayosma** [comment]
Thanks @monoppa!

@fredguth yep! there's a branch, just needs to pull the updates from main branch

**Comment by arjayosma** [comment]
@maybesmurf got it! I'll prepare the base project for typescript migration. I don't mind the convention for now. thanks for taking the time. I'll get back to you on this

**Comment by xbyyz** [comment]
so,There is a typescript branch, right?

**Comment by arjayosma** [comment]
@xbyyz: yes, there's a TS branch but it'll be removed today.

Here's the TS project: https://github.com/nextacular/nextacular-ts

It's still experimental, haven't tested much of it, but have added the necessary TS configurations for a Next.JS project.

The project will build though if you set the `tsconfig.json` file's `strict` mode to `false`.

CC: @maybesmurf, @fredguth
